version: '3.8'

networks:
  corp:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - blog-app-nx:base
      dockerfile: ./apps/backend/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        BUILD_FLAG: --prod
    image: backend:prod
    ports:
      - ${API_DOCKER_PORT:-5000}:${PORT:-5000}
    volumes:
      - ./apps/backend:/app/builder/apps/backend
    env_file: ./.env
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - corp
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.21
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        BUILD_FLAG: --prod
    image: frontend:prod
    ports:
      - ${APP_DOCKER_PORT:-4200}:80
    environment:
      NODE_ENV: ${NODE_ENV}
    env_file: ./.env
    depends_on:
      - backend
    networks:
      - corp
    restart: on-failure
