version: '3.8'

networks:
  corp:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - blog-app-nx:base
      dockerfile: ./apps/backend/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: backend:dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'development'
      PORT: 4939
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - corp
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.21
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: frontend:dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    depends_on:
      - backend
    networks:
      - corp
    restart: on-failure

  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    networks:
      - corp
    restart: on-failure
