version: '3.8'

networks:
  corp:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - blog-app-nx:base
      dockerfile: ./apps/backend/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: backend:dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'development'
      PORT: 4939
    networks:
      - corp
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.21
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: frontend:dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    networks:
      - corp
    restart: on-failure
