version: '3.8'

networks:
  corp:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
      args:
        NODE_ENV: 'production'
        BUILD_FLAG: ''
    image: backend:prod
    # ports:
    #   - 5000:5000
    environment:
      NODE_ENV: 'production'
      PORT: 3333
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - corp
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.21
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NODE_ENV: 'production'
        BUILD_FLAG: ''
    image: frontend:prod
    ports:
      - 4200:80
    environment:
      NODE_ENV: 'production'
      PORT: 4200
    depends_on:
      - backend
    networks:
      - corp
    restart: on-failure

  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    networks:
      - corp
    restart: on-failure
