version: '3.8'

services:
  backend:
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    networks:
      - corp
    restart: on-failure
