# Monorepo deploy vercel
name: Deploy Vercel

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]
  create:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout and install
      - name: checkout
        uses: actions/checkout@v2

      - name: Branch name
        id: vars
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)

      - name: Check outputs
        run: |
          echo ${{ steps.vars.outputs.SHA_SHORT }}
          echo ${{ steps.vars.outputs.SOURCE_NAME }}

      - name: NPM Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm ci

      # Build and deploy
      - name: Build
        run: NX_REACT_APP_VERSION=${{ steps.vars.outputs.SOURCE_NAME }}.${{ steps.vars.outputs.SHA_SHORT }} npm run build

      - name: Deploy staging
        uses: amondnet/vercel-action@v20
        id: vercel-action-staging-preview
        if: ${{ (github.event_name == 'push') && (github.ref_name ==  'staging') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      - name: Deploy tagged staging
        uses: amondnet/vercel-action@v20
        id: vercel-action-tagged-staging
        if: ${{ (github.event_name == 'create') && startsWith(github.ref, 'refs/tags/sv') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          alias-domains: staging.achromik.com

      - name: Deploy production preview
        uses: amondnet/vercel-action@v20
        id: vercel-action-production-preview
        if: ${{ (github.event_name == 'pull_request') && contains(github.ref, 'main') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      - name: Deploy production
        uses: amondnet/vercel-action@v20
        id: vercel-action-production
        if: ${{ (github.event_name == 'create') && startsWith(github.ref, 'refs/tags/v') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
