# Monorepo deploy vercel
name: Deploy Vercel

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Exit if not tag created
        if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v') }}
        run: exit -1

      - name: Get version
        id: vars
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)

      - name: NPM Cache
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm ci

      # Build and deploy
      - name: Build
        run: NX_REACT_APP_VERSION=${{ steps.vars.outputs.SOURCE_NAME }}.${{ steps.vars.outputs.SHA_SHORT }} npm run build

      - name: Deploy PR staging preview
        uses: amondnet/vercel-action@v20
        id: vercel-action-staging-preview
        if: ${{ github.base_ref == 'staging' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      - name: Deploy tagged staging
        uses: amondnet/vercel-action@v20
        id: vercel-action-tagged-staging
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          alias-domains: staging.achromik.com

      - name: Deploy PR production preview
        uses: amondnet/vercel-action@v20
        id: vercel-action-production-preview
        if: ${{ github.base_ref == 'main' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      - name: Deploy production
        uses: amondnet/vercel-action@v20
        id: vercel-action-production
        if: ${{  startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'rc') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
